# Generated by Django 6.0.2 on 2026-03-01 04:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('initiatives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_json', models.JSONField()),
                ('description_json', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiatives.initiative')),
            ],
        ),
        migrations.CreateModel(
            name='FormVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('schema_json', models.JSONField()),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='forms_engine.form')),
            ],
            options={
                'unique_together': {('form', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_key', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('select', 'Select'), ('textarea', 'Textarea'), ('image', 'Image'), ('file', 'File')], max_length=50)),
                ('label_json', models.JSONField()),
                ('placeholder_json', models.JSONField(blank=True, null=True)),
                ('help_text_json', models.JSONField(blank=True, null=True)),
                ('validation_json', models.JSONField(blank=True, null=True)),
                ('options_json', models.JSONField(blank=True, null=True)),
                ('order_index', models.IntegerField(default=0)),
                ('is_required', models.BooleanField(default=False)),
                ('form_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='forms_engine.formversion')),
            ],
        ),
    ]
