# Generated by Django 6.0.2 on 2026-03-01 04:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow_state', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('coordinator_review', 'Coordinator Review'), ('lead_review', 'Lead Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmission', 'Resubmission Required')], default='draft', max_length=50)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms_engine.formversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionFieldValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_key', models.CharField(max_length=255)),
                ('value_json', models.JSONField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='submission_files/')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='submissions.submission')),
            ],
        ),
    ]
